import {
  CollectionCenter,
  Customer,
  Expense,
  LedgerEntry,
  MilkCollection,
  MilkRate,
  NotificationItem,
  Payment,
  Settlement,
  User,
  BusinessSettings,
} from '../types/index.js';

export interface DatabaseState {
  users: User[];
  collection_centers: CollectionCenter[];
  customers: Customer[];
  milk_rates: MilkRate[];
  milk_collections: MilkCollection[];
  payments: Payment[];
  settlements: Settlement[];
  ledger_entries: LedgerEntry[];
  expenses: Expense[];
  notifications: NotificationItem[];
  settings: BusinessSettings;
}

export function getInitialSeedData(): DatabaseState {
  // 4 Core Collection Centers
  const centers: CollectionCenter[] = [
    {
      id: 'c1',
      name: 'Srivilliputtur Center',
      location: 'Madurai Road, Srivilliputtur',
      code: 'SVPR',
      phone: '+91 98421 11220',
      is_active: true,
      created_at: '2026-01-10T08:00:00Z',
    },
    {
      id: 'c2',
      name: 'Rajapalayam Center',
      location: 'Tenkasi Highway, Rajapalayam',
      code: 'RJPM',
      phone: '+91 98421 11221',
      is_active: true,
      created_at: '2026-01-15T08:00:00Z',
    },
    {
      id: 'c3',
      name: 'Sivakasi Center',
      location: 'Sattur Road, Sivakasi',
      code: 'SVKS',
      phone: '+91 98421 11222',
      is_active: true,
      created_at: '2026-02-01T08:00:00Z',
    },
    {
      id: 'c4',
      name: 'Virudhunagar Center',
      location: 'Collectorate Junction, Virudhunagar',
      code: 'VDR',
      phone: '+91 98421 11223',
      is_active: true,
      created_at: '2026-02-10T08:00:00Z',
    },
  ];

  // 3 Staff/Admin Users
  const users: User[] = [
    {
      id: 'u1',
      name: 'Admin',
      mobile: '9842100001',
      email: 'milkhub@admin.com',
      password: 'Admin@123',
      role: 'admin',
      collection_center_id: 'c1',
      status: 'active',
      last_login: new Date().toISOString(),
      created_at: '2026-01-01T00:00:00Z',
    },
    {
      id: 'u2',
      name: 'Murugan S (Staff)',
      mobile: '9842100002',
      email: 'staff@milkhub.com',
      password: 'staff',
      role: 'staff',
      collection_center_id: 'c1',
      status: 'active',
      last_login: new Date().toISOString(),
      created_at: '2026-01-05T00:00:00Z',
    },
    {
      id: 'u3',
      name: 'Selvi M (Staff)',
      mobile: '9842100003',
      email: 'staff2@milkhub.com',
      password: 'staff',
      role: 'staff',
      collection_center_id: 'c2',
      status: 'active',
      last_login: new Date().toISOString(),
      created_at: '2026-01-10T00:00:00Z',
    },
  ];

  // Exactly 5 Real Registered Suppliers
  const customers: Customer[] = [
    {
      id: 'cust_1',
      customer_code: 'MILK001',
      name: 'Kumar',
      mobile: '9876543210',
      address: '12, North Street, Srivilliputtur',
      village: 'Srivilliputtur',
      cow_count: 4,
      buffalo_count: 2,
      default_session: 'both',
      collection_center_id: 'c1',
      status: 'active',
      notes: 'A2 Cow Milk & Buffalo supplier',
      created_at: '2026-01-01T00:00:00Z',
    },
    {
      id: 'cust_2',
      customer_code: 'MILK002',
      name: 'Mani',
      mobile: '9876543211',
      address: '45, East Car Street, Rajapalayam',
      village: 'Rajapalayam',
      cow_count: 6,
      buffalo_count: 0,
      default_session: 'morning',
      collection_center_id: 'c2',
      status: 'active',
      notes: 'Pure Cow Milk supplier',
      created_at: '2026-01-05T00:00:00Z',
    },
    {
      id: 'cust_3',
      customer_code: 'MILK003',
      name: 'Selvi',
      mobile: '9876543212',
      address: '8, Gandhi Nagar, Sivakasi',
      village: 'Sivakasi',
      cow_count: 3,
      buffalo_count: 3,
      default_session: 'both',
      collection_center_id: 'c3',
      status: 'active',
      notes: 'Daily morning & evening supplier',
      created_at: '2026-01-10T00:00:00Z',
    },
    {
      id: 'cust_4',
      customer_code: 'MILK004',
      name: 'Lakshmi',
      mobile: '9876543213',
      address: '24, Bazaar Road, Virudhunagar',
      village: 'Virudhunagar',
      cow_count: 5,
      buffalo_count: 1,
      default_session: 'both',
      collection_center_id: 'c4',
      status: 'active',
      notes: 'High SNF milk supplier',
      created_at: '2026-01-15T00:00:00Z',
    },
    {
      id: 'cust_5',
      customer_code: 'MILK005',
      name: 'Murugan',
      mobile: '9876543214',
      address: '102, Sannathi Street, Srivilliputtur',
      village: 'Srivilliputtur',
      cow_count: 2,
      buffalo_count: 4,
      default_session: 'evening',
      collection_center_id: 'c1',
      status: 'active',
      notes: 'Buffalo milk specialist',
      created_at: '2026-01-20T00:00:00Z',
    },
  ];

  // Milk Rate Formula
  const milk_rates: MilkRate[] = [
    {
      id: 'rate_1',
      pricing_type: 'fat_snf',
      base_rate: 42.0,
      standard_fat: 4.2,
      standard_snf: 8.5,
      fat_rate: 3.5,
      snf_rate: 2.0,
      effective_date: '2026-09-01',
      updated_by: 'Kumar Raja (Admin)',
      is_active: true,
      notes: 'Standard Tamil Nadu cooperative dynamic pricing formula',
    },
  ];

  const today = new Date().toISOString().split('T')[0];

  // Exactly 5 Milk Collections (3 Box 1 Center Registered + 2 Box 2 Direct Walk-in)
  const milk_collections: MilkCollection[] = [
    // Box 1: Center Registered Supplier 1
    {
      id: 'col_1',
      customer_id: 'cust_1',
      supplier_type: 'REGISTERED',
      collection_center_id: 'c1', // Srivilliputtur
      date: today,
      session: 'morning',
      animal_type: 'cow',
      quantity: 10.0,
      fat_percentage: 4.2,
      snf_percentage: 8.5,
      calculated_rate: 42.0,
      total_amount: 420.0,
      payment_status: 'PENDING',
      status: 'collected',
      collected_by: 'Murugan S',
      notes: 'Morning collection can #1',
      created_at: `${today}T06:45:00Z`,
    },
    // Box 1: Center Registered Supplier 2
    {
      id: 'col_2',
      customer_id: 'cust_2',
      supplier_type: 'REGISTERED',
      collection_center_id: 'c2', // Rajapalayam
      date: today,
      session: 'morning',
      animal_type: 'cow',
      quantity: 12.0,
      fat_percentage: 4.4,
      snf_percentage: 8.6,
      calculated_rate: 42.9,
      total_amount: 514.8,
      payment_status: 'PENDING',
      status: 'collected',
      collected_by: 'Selvi M',
      notes: 'Pure cow milk batch',
      created_at: `${today}T07:15:00Z`,
    },
    // Box 1: Center Registered Supplier 3
    {
      id: 'col_3',
      customer_id: 'cust_3',
      supplier_type: 'REGISTERED',
      collection_center_id: 'c3', // Sivakasi
      date: today,
      session: 'evening',
      animal_type: 'cow',
      quantity: 8.5,
      fat_percentage: 4.0,
      snf_percentage: 8.5,
      calculated_rate: 41.3,
      total_amount: 351.05,
      payment_status: 'PENDING',
      status: 'collected',
      collected_by: 'Murugan S',
      notes: 'Evening session delivery',
      created_at: `${today}T17:30:00Z`,
    },
    // Box 2: Direct / Walk-in Supplier 1 (Paid)
    {
      id: 'col_4',
      customer_id: null,
      supplier_type: 'DIRECT',
      walk_in_name: 'Ramesh (Direct)',
      walk_in_mobile: '9842155667',
      collection_center_id: 'c1', // Srivilliputtur
      date: today,
      session: 'morning',
      animal_type: 'cow',
      quantity: 15.0,
      fat_percentage: 4.3,
      snf_percentage: 8.6,
      calculated_rate: 42.0,
      total_amount: 630.0,
      payment_status: 'PAID',
      status: 'collected',
      collected_by: 'Murugan S',
      notes: 'Spot cash counter settlement',
      created_at: `${today}T08:15:00Z`,
    },
    // Box 2: Direct / Walk-in Supplier 2 (Pending)
    {
      id: 'col_5',
      customer_id: null,
      supplier_type: 'DIRECT',
      walk_in_name: 'Murugesan (Direct)',
      walk_in_mobile: '9842188990',
      collection_center_id: 'c2', // Rajapalayam
      date: today,
      session: 'evening',
      animal_type: 'cow',
      quantity: 18.0,
      fat_percentage: 4.2,
      snf_percentage: 8.5,
      calculated_rate: 42.0,
      total_amount: 756.0,
      payment_status: 'PENDING',
      status: 'collected',
      collected_by: 'Selvi M',
      notes: 'Evening direct walk-in',
      created_at: `${today}T18:00:00Z`,
    },
  ];

  // Exactly 5 Payments
  const payments: Payment[] = [
    {
      id: 'pay_1',
      customer_id: 'cust_1',
      collection_center_id: 'c1',
      date: '2026-09-15',
      amount: 1000.0,
      payment_method: 'upi',
      reference_no: 'UPI/984210001/8871',
      status: 'completed',
      notes: 'Mid-month settlement advance',
      created_by: 'Kumar Raja',
      created_at: '2026-09-15T11:00:00Z',
    },
    {
      id: 'pay_2',
      customer_id: 'cust_2',
      collection_center_id: 'c2',
      date: '2026-09-15',
      amount: 1500.0,
      payment_method: 'bank_transfer',
      reference_no: 'NEFT5589120',
      status: 'completed',
      notes: 'Direct bank deposit',
      created_by: 'Kumar Raja',
      created_at: '2026-09-15T11:30:00Z',
    },
    {
      id: 'pay_3',
      customer_id: 'cust_3',
      collection_center_id: 'c3',
      date: '2026-09-18',
      amount: 800.0,
      payment_method: 'cash',
      reference_no: 'CSH-0988',
      status: 'completed',
      notes: 'Cash payout at Sivakasi counter',
      created_by: 'Murugan S',
      created_at: '2026-09-18T10:15:00Z',
    },
    {
      id: 'pay_4',
      customer_id: 'cust_4',
      collection_center_id: 'c4',
      date: '2026-09-20',
      amount: 1200.0,
      payment_method: 'upi',
      reference_no: 'UPI/984210004/3321',
      status: 'completed',
      notes: 'UPI transfer to mobile',
      created_by: 'Kumar Raja',
      created_at: '2026-09-20T12:00:00Z',
    },
    {
      id: 'pay_5',
      customer_id: 'cust_5',
      collection_center_id: 'c1',
      date: '2026-09-21',
      amount: 900.0,
      payment_method: 'cash',
      reference_no: 'CSH-1045',
      status: 'completed',
      notes: 'Cash payout at counter',
      created_by: 'Murugan S',
      created_at: '2026-09-21T15:30:00Z',
    },
  ];

  // Ledger Entries
  const ledger_entries: LedgerEntry[] = [
    {
      id: 'led_1',
      customer_id: 'cust_1',
      date: '2026-09-01',
      description: 'Opening Balance',
      debit: 0,
      credit: 0,
      running_balance: 0,
      reference_type: 'opening',
      created_at: '2026-09-01T00:00:00Z',
    },
    {
      id: 'led_2',
      customer_id: 'cust_1',
      date: '2026-09-10',
      description: 'Milk Collection (Cumulative delivery)',
      milk_quantity: 45.0,
      debit: 1890.0,
      credit: 0,
      running_balance: 1890.0,
      reference_type: 'collection',
      created_at: '2026-09-10T18:00:00Z',
    },
    {
      id: 'led_3',
      customer_id: 'cust_1',
      date: '2026-09-15',
      description: 'Payment (UPI to 9876543210@okaxis)',
      debit: 0,
      credit: 1000.0,
      running_balance: 890.0,
      reference_type: 'payment',
      reference_id: 'pay_1',
      created_at: '2026-09-15T11:00:00Z',
    },
    {
      id: 'led_4',
      customer_id: 'cust_1',
      date: today,
      description: 'Milk Collection (Morning 10.0L @ ₹42.00)',
      milk_quantity: 10.0,
      debit: 420.0,
      credit: 0,
      running_balance: 1310.0,
      reference_type: 'collection',
      reference_id: 'col_1',
      created_at: `${today}T06:45:00Z`,
    },
    {
      id: 'led_5',
      customer_id: 'cust_2',
      date: '2026-09-10',
      description: 'Milk Collection (Delivery batch)',
      milk_quantity: 48.0,
      debit: 2000.0,
      credit: 0,
      running_balance: 2000.0,
      reference_type: 'collection',
      created_at: '2026-09-10T18:00:00Z',
    },
    {
      id: 'led_6',
      customer_id: 'cust_2',
      date: '2026-09-15',
      description: 'Payment (NEFT to Bank Account)',
      debit: 0,
      credit: 1500.0,
      running_balance: 500.0,
      reference_type: 'payment',
      reference_id: 'pay_2',
      created_at: '2026-09-15T11:30:00Z',
    },
    {
      id: 'led_7',
      customer_id: 'cust_2',
      date: today,
      description: 'Milk Collection (Morning 12.0L @ ₹42.90)',
      milk_quantity: 12.0,
      debit: 514.8,
      credit: 0,
      running_balance: 1014.8,
      reference_type: 'collection',
      reference_id: 'col_2',
      created_at: `${today}T07:15:00Z`,
    },
  ];

  // Settlements
  const settlements: Settlement[] = [
    {
      id: 'stl_1',
      settlement_code: 'SET-202608-001',
      customer_id: 'cust_1',
      collection_center_id: 'c1',
      month_year: '2026-08',
      from_date: '2026-08-01',
      to_date: '2026-08-31',
      total_milk: 310.5,
      total_amount: 13041.0,
      previous_paid: 12500.0,
      pending_amount: 541.0,
      settled_amount: 541.0,
      status: 'settled',
      confirmed_at: '2026-09-02T10:00:00Z',
      confirmed_by: 'Kumar Raja',
    },
  ];

  // Exactly 5 Expenses
  const expenses: Expense[] = [
    {
      id: 'exp_1',
      collection_center_id: 'c1',
      date: today,
      category: 'transport',
      description: 'Milk van diesel - Route 2 (Watrap to Srivilliputtur)',
      amount: 1850.0,
      payment_method: 'upi',
      notes: 'IOCL petrol bunk diesel',
      added_by: 'Murugan S',
      created_at: `${today}T09:30:00Z`,
    },
    {
      id: 'exp_2',
      collection_center_id: 'c1',
      date: today,
      category: 'electricity',
      description: 'Chilling Plant Generator Backup Diesel (20L)',
      amount: 1980.0,
      payment_method: 'cash',
      notes: 'Power cut backup for bulk milk cooler',
      added_by: 'Kumar Raja',
      created_at: `${today}T12:00:00Z`,
    },
    {
      id: 'exp_3',
      collection_center_id: 'c2',
      date: '2026-09-20',
      category: 'maintenance',
      description: 'Lactometer calibration and Gerber milk tester chemicals',
      amount: 1450.0,
      payment_method: 'cash',
      notes: 'Monthly laboratory test kit restock',
      added_by: 'Selvi M',
      created_at: '2026-09-20T14:00:00Z',
    },
    {
      id: 'exp_4',
      collection_center_id: 'c1',
      date: '2026-09-05',
      category: 'salary',
      description: 'Collection staff advance disbursement',
      amount: 5000.0,
      payment_method: 'bank_transfer',
      notes: 'Monthly advance for dock operator',
      added_by: 'Kumar Raja',
      created_at: '2026-09-05T10:00:00Z',
    },
    {
      id: 'exp_5',
      collection_center_id: 'c3',
      date: '2026-09-12',
      category: 'equipment',
      description: 'Stainless Steel Milk Cans (40 Litres x 2 nos)',
      amount: 6400.0,
      payment_method: 'bank_transfer',
      notes: 'New supplier food-grade cans',
      added_by: 'Kumar Raja',
      created_at: '2026-09-12T16:00:00Z',
    },
  ];

  // 4 Notifications
  const notifications: NotificationItem[] = [
    {
      id: 'notif_1',
      title: 'Payment Pending for Kumar (MILK001)',
      message: 'Pending balance of ₹1,310.00 ready for September cycle settlement.',
      type: 'payment',
      read: false,
      timestamp: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    },
    {
      id: 'notif_2',
      title: 'Monthly Settlement Due',
      message: 'Cycle 16-30 September settlements scheduled for generation.',
      type: 'settlement',
      read: false,
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    },
    {
      id: 'notif_3',
      title: 'Milk Rate Updated',
      message: 'Base rate set to ₹42.00/L with Fat/SNF dynamic index.',
      type: 'rate',
      read: true,
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    },
    {
      id: 'notif_4',
      title: 'Daily Collection Active',
      message: '5 collections active across centers (3 Registered + 2 Direct).',
      type: 'collection',
      read: true,
      timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    },
  ];

  // Settings
  const settings: BusinessSettings = {
    business_name: 'MilkHub Dairy & Milk Collection',
    tagline: 'Precision Dairy Operations & Farmer Management Platform • Developed by Gen Z Neural-X',
    brand_code: 'MILKHUB',
    phone: '+91 98421 00001',
    email: 'operations@milkhubdairy.com',
    address: '42, Dairy Development Road, Near Milk Chilling Center',
    district: 'Virudhunagar',
    state: 'Tamil Nadu',
    default_pricing_mode: 'fat_snf',
    base_cow_rate: 42.0,
    base_buffalo_rate: 52.0,
    default_language: 'en',
    whatsapp_enabled: true,
    currency_symbol: '₹',
  };

  return {
    users,
    collection_centers: centers,
    customers,
    milk_rates,
    milk_collections,
    payments,
    settlements,
    ledger_entries,
    expenses,
    notifications,
    settings,
  };
}
